### ISSUE TITLE
Stop flooding the issues with the same Language requests

### ISSUE THREAD

**Issue by TheBrenny** [atom-community/atom-script#1004]
Trying to find genuine issues, and I can only see duplicate feature request issues, such as "Add support for HTML" and the like.

I can't fully remember, but there was a package that told the user if an issue of the same type had already been opened, and that they could check it out. Can AtomScript implement the same sort of feature?

**Comment by nixel2007** [comment]
Hi, @TheBrenny! Could you provide some links to that package you mentioned? I could try to reimplement it for script. 

And yes, duplicate issues are annoying :(

**Comment by TheBrenny** [comment]
@nixel2007, Just to name a few that I see on the first page: 
- #968 
- #970 
- #984 
- #996 
- #998 

I'll update the list as I scroll on through. :stuck_out_tongue_closed_eyes:

**Comment by nixel2007** [comment]
@TheBrenny sorry, I mean link to that part of your message:
> but there was a package that told the user if an issue of the same type had already been opened

**Comment by TheBrenny** [comment]
> @TheBrenny sorry, I mean link to that part of your message:
> 
> > but there was a package that told the user if an issue of the same type had already been opened

Big sorry, but no, I have no idea. :( Maybe use tags when creating issues, and then search for the tags before giving the choice to make a new issue?

**Comment by aminya** [comment]
The code which resulted in issue creation was removed. We can close this now.
