### ISSUE TITLE
Doesn't show Chinese character properly

### ISSUE THREAD

**Issue by wuqs-net** [atom-community/atom-script#1268]
When I run a java file with error, the Chinese characters in error message are not shown properly.  
Basically the error complains that I need to add a semicolon at the end of statement.

It is supposed to show this (when run in cmd):
![image](https://cloud.githubusercontent.com/assets/22854142/23685218/e48107f4-0370-11e7-9da7-ff429ff5f3c6.png)

It is now showing this (when run in Atom with Script):
![image](https://cloud.githubusercontent.com/assets/22854142/23685228/f65133aa-0370-11e7-8626-76c6e498840e.png)

I'm not sure what the problem is, but I think it has something to do with the encoding stuff.

Thanks in advance!

**Comment by chwdy** [comment]
having the same problem on osx

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
