### ISSUE TITLE
Can't run Python and Java 

### ISSUE THREAD

**Issue by sannegeraets** [atom-community/atom-script#1274]
I installed Script and now with the key-combo Ctrl + Shift + B, Atom should run the code. But with a Pythoncode, I get the error: 'python' is not recognized as an internal or external command, operable program or batch file. With a Javacode, I get the error: 'cmd' is not recognized as an internal or external command, operable program or batch file.
How can I fix this problem?

Thanks for the help.

**Comment by sannegeraets** [comment]
problem with running scripts

**Comment by stendarr** [comment]
Have you made sure that `python` is a PATH variable?

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
