### ISSUE TITLE
Unable to compile and run Kotlin files

### ISSUE THREAD

**Issue by Nearoo** [atom-community/atom-script#1366]
Hi! I'm trying to setup Kotlin for the Atom Editor, but I'm failing.

I installed the Kotlin compiler as described [here](https://kotlinlang.org/docs/tutorials/command-line.html): Unzip files somewhere, add `bin` folder to `Path`. I then tried to create the example that is described on that very same page - a simple "Hello World" script, but I'm unable to.

When I execute the script in Atom using Script (`Ctrl + Shift + B`), I get the following output:

    error: source file or directory not found: [C:PathTo]
    error: source file or directory not found: [MyFile]
    error: source file or directory not found: [SplitAcross]
    error: source file or directory not found: [MultipleLines]
    error: source file or directory not found: [WithoutSlashOrSpace]

There are obviously some `"`missing somewhere, I don't know where to add them though.

So I tried entering the command on my own by changing the run options. Just the way it's described on the website: `kotlinc hello.kt -include-runtime -d hello.jar` which also returns an error:

    error: invalid argument: -c
    info: use -help for more information

Compilation and execution works fine in the command line itself. Thanks for your time.

* **OS:** Windows 10
* **Atom Version:** 1.18.0
* **Script Version:** 3.15.0

**Comment by danielbayley** [comment]
@Nearoo This should be fixed in #1451… Please test and report back.

**Comment by LuciferChase** [comment]
It is still not fixed. Any new development or help?

**Comment by weather-tracker** [comment]
I'm new to all this but that is the same error I got. 
text editor vscode
compiler        Kotlin-native-windows-1.4.32.zip from JetBrains GitHub      https://github.com/JetBrains/kotlin/releases/tag/v1.4.32
my compiler camand      kotlinc.bat helloworld.kt -target mingw_x64 -d "hellow world/hello world.jar"
error: invalid argument: -d
info: use -help for more information

**Comment by weather-tracker** [comment]
found solution need new camand now find it here
 https://kotlinlang.org/docs/native-command-line-compiler.html#compile-the-code-from-the-console

**Comment by weather-tracker** [comment]
Ok.
I was actually using the complier in the cmd not in this but will try and do that.

**Comment by weather-tracker** [comment]
by pr is pull request
