### ISSUE TITLE
incorrect chinese display when running java

### ISSUE THREAD

**Issue by chwdy** [atom-community/atom-script#1445]
my system is set to chinese so java output chinese log in terminal. It works well when in terminal, but it messed up when output in Atom
![image](https://user-images.githubusercontent.com/15193485/31353331-28931e3a-ad00-11e7-9e5d-77ad9068dd32.png)

**Comment by chwdy** [comment]
on mac os

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
