### ISSUE TITLE
issue. Processing. Folder names with spaces

### ISSUE THREAD

**Issue by kylemurphey** [atom-community/atom-script#1543]
I think I am running into an issue similar issue  #[1233](https://github.com/rgbkrk/atom-script/issues/1233) with spaces. 

I am trying to run Processing.org on my Mac, and noticed that script enters this:
`[Command: processing-java '--sketch='/Users/username/Google Drive/Processing/helloworld'' --run]`and it returns the error :
`'/Users/username/Google Drive/Processing/helloworld' does not exist.`

However if I enter this in terminal:
`processing-java '--sketch='/Users/username/Google\ Drive/Processing/helloworld'' --run`
my sketch runs just fine.

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
