### ISSUE TITLE
Directory is not recognized

### ISSUE THREAD

**Issue by doubleUTF** [atom-community/atom-script#1545]
I can't seem to get javascript files running but somehow other files are ok. Already made sure node path is registered as it can be run from any directory in cmd. Example of working files:

Typescript working:
```
[Command: ts-node F:\App_Projects\test\test.ts]
number
[Finished in 0.616s]
```

Python working:
```
[Command: python -u F:\App_Projects\test\test.py]
Hello world
[Finished in 0.088s]

```
Javascript error:
```
[Command: cmd '/c C:\Users\Big D\.atom\packages\script\node_modules\.bin\babel --filename C:\Users\Big D\.atom\packages\script\node_modules\.bin\babel < F:\App_Projects\test\test.js| node']
'C:\Users\Big' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.081s]
```

I don't get why running JS has a different and verbose command. I've tried reinstalling atom-script , run 'atom .' from command to ensure access to system variables but to no avail. Please help! Running on Win7, Node v9.5.0

**Comment by Abhay520** [comment]
Have same issue. Did you solve your problem?
