### ISSUE TITLE
Atom isuue: javac: file not found: File.java

### ISSUE THREAD

**Issue by Sebas16171** [atom-community/atom-script#1556]
Hi
I'm starting on Java language on my Windows 10x64 using atom with script plugin but I've had this issue

> javac: file not found: File1.java
> Usage: javac options source files
> use -help for a list of possible options
> [Finished in 0.472s]`

I've already installed jre and jdk is on my path but still not working :/
Please help & thanks btw

**Comment by aryansaw03** [comment]
I am encountering the same problem

**Comment by gopanarayan** [comment]
me too

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
