### ISSUE TITLE
Some installed packages could not be loaded because they contain native modules that were compiled for an earlier version of Atom.

### ISSUE THREAD

**Issue by Albert-Z-Guo** [atom-community/atom-script#1577]
Atom version: 1.25.0 x64

node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.2/fse-v1.1.2-electron-v1.7-darwin-x64.tar.gz 
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.2 and electron@1.7.11 (electron-v1.7 ABI) (falling back to source compile with node-gyp) 
c++: error: unrecognized command line option '-stdlib=libc++'
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.4.0
gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/.bin/node-gyp" "build" "--fallback-to-build" "--module=/Users/Albert_Guo/.atom/packages/script/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/Albert_Guo/.atom/packages/script/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64"
gyp ERR! cwd /Users/Albert_Guo/.atom/packages/script/node_modules/fsevents
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Applications/Atom.app/Contents/Resources/app/apm/bin/node /Applications/Atom.app/Contents/Resources/app/apm/bin/../node_modules/.bin/node-gyp build --fallback-to-build --module=/Users/Albert_Guo/.atom/packages/script/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64/fse.node --module_name=fse --module_path=/Users/Albert_Guo/.atom/packages/script/node_modules/fsevents/lib/binding/Release/electron-v1.7-darwin-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Albert_Guo/.atom/packages/script/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Darwin 17.4.0
node-pre-gyp ERR! command "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Users/Albert_Guo/.atom/packages/script/node_modules/fsevents/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Albert_Guo/.atom/packages/script/node_modules/fsevents
node-pre-gyp ERR! node -v v6.9.5
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok 

npm ERR! Darwin 17.4.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Albert_Guo/.atom/.apm/.apmrc" "--userconfig" "/Users/Albert_Guo/.atom/.apmrc" "rebuild" "--runtime=electron" "--target=1.7.11" "--arch=x64"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! fsevents@1.1.2 install: `node install`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fsevents@1.1.2 install script 'node install'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fsevents package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fsevents
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fsevents
npm ERR! There is likely additional logging output above.

**Comment by Albert-Z-Guo** [comment]
<img width="1440" alt="screen shot 2018-03-24 at 18 04 41" src="https://user-images.githubusercontent.com/11432634/37869433-df27d388-2f8d-11e8-8d4c-607cf526dfba.png">

**Comment by Albert-Z-Guo** [comment]
I updated my Atom to 1.25.0 x64 and somehow script 3.17.3 does not work any more.

**Comment by mkatychev** [comment]
@Albert-Z-Guo reinstalling script then rebuilding it solved this issue for me

**Comment by Albert-Z-Guo** [comment]
I rebuilt the package and the problem is now solved.

Thanks @mkatychev!

**Comment by stephaniemdavis** [comment]
@mkatychev I uninstalled, reinstalled and rebuilt and my problem has been resolved. 
**Thank You**

**Comment by chrishiestand** [comment]
I had a similar issue but totally different error message about the wrong version of python. But I uninstalled, restarted atom, and reinstalled and it the problem build issue went away. Strange but glad the problem is fixed.

And this issue can be closed since the OP reported the problem solved, right?
