### ISSUE TITLE
The system cannot find the file specified on windows (but works when I remove the space in the file name)

### ISSUE THREAD

**Issue by WiliTest** [atom-community/atom-script#1600]
I only have this issue when I run javascript (no problem with python).  When I remove the space from the file name it works as expected

In the setting the menu is set to `Directory of the script`

On windows 10x64 with script 3.17.3

**Comment by picorealm** [comment]
I'm having the same issue with Kotlin.  Source code in directories whose pathnames contain spaces will not run.

**Comment by brettsherwood12** [comment]
what about when the space is in c:/users/user name and you cannot remove the space? at least without a lot lot of work...
