### ISSUE TITLE
Unable to execute Java files

### ISSUE THREAD

**Issue by Mr-DJ** [atom-community/atom-script#1718]
I have tried to solve this problem by looking for solutions online but the problem still persists. Here are some things that I tried and checked ~

+ check if java is on the system environment variable list, the `jdk<version>/bin` is linked to PATH.
+ added atom to system vars. as the docs requires of users to run ATOM from the terminal.
EDIT : I got the files to run, but they won't take any inputs.
I am still unable to execute Java files efficiently. I'm able to print data but I'm **unable** to _take in inputs_ or _call any functions_

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
