### ISSUE TITLE
Not able to run the java script through atom editor, I tried to run the java through command prompt and it is executing fine

### ISSUE THREAD

**Issue by EgeSysln** [atom-community/atom-script#1828]

**Comment by EgeSysln** [comment]
**That's the output of it:**
error: file not found: GalToLit.java
Usage: javac <options> <source files>
use --help for a list of possible options
[Finished in 0.333s]

**Comment by EgeSysln** [comment]
I think this issue occurs due to not changing directory.

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
