### ISSUE TITLE
How do I actually set the command for Java? 

### ISSUE THREAD

**Issue by KreedM** [atom-community/atom-script#1961]
I'm trying to compile a .java file that uses javafx.
I do alt shift control o, and pasted this into the command box:
cmd javac --module-path %PATH_TO_FX% --add-modules javafx.controls HelloFX.java
As soon as I click run I get a slew of errors as if I only did javac HelloFX.java
I checked the log and saw that the command actually inputted was:
[Command: cmd javac --module-path %PATH_TO_FX% --add-modules javafx.controls HelloFX.java '/c javac -Xlint HelloFX.java && java HelloFX']
Why is the error happening?
I was able to do it in cmd on Windows so I don't know what's wrong.

**Comment by KreedM** [comment]
I do have %PATH_TO_FX% set to "C:\Program Files\Java\javafx-sdk-11.0.2\lib" and C:\Program Files\Java\jdk-11.0.4\bin in path.  As a side note without the javafx modules I was able to run a simple hello world program using System.out.println and without configuring run options.

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
