### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by echomyself** [atom-community/atom-script#2082]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.45.0 x64
**Electron**: 4.2.7
**OS**: Unknown Windows version
**Thrown From**: [script](https://github.com/rgbkrk/atom-script) package 3.25.0

### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At C:\Users\夏凌宇\.atom\packages\script\lib\runner.js:137

TypeError: Cannot read property 'replace' of undefined
    at Runner.fillVarsInArg (/packages/script/lib/runner.js:137:17)
    at /packages/script/lib/runner.js:168:34
    at Array.map (<anonymous>)
    at Runner.args (/packages/script/lib/runner.js:168:18)
    at Runner.run (/packages/script/lib/runner.js:26:23)
    at Runtime.execute (/packages/script/lib/runtime.js:78:17)
    at HTMLElement.scriptRun (/packages/script/lib/script.js:98:40)
    at CommandRegistry.handleCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:349290)
    at KeymapManager.dispatchCommandEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1254747)
    at KeymapManager.handleKeyboardEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:1250881)
    at WindowEventHandler.handleDocumentKeyEvent (~/AppData/Local/atom/app-1.45.0/resources/app/static/<embedded>:11:284496)
```

### Commands

```
     -0:42.4.0 script:run (input.hidden-input)
```

### Non-Core Packages

```
script 3.25.0 
```

**Comment by Kishore-KS** [comment]
Same issue

**Comment by Shreyas-loki** [comment]
same issue

**Comment by sblaker** [comment]
Same issue :/

**Comment by XIDEMOIX** [comment]
same issue ://///////////////////

**Comment by moaz-ahmed** [comment]
same :"(

**Comment by Ken219** [comment]
same here :'(

**Comment by LSTPro** [comment]
same issue

**Comment by Gradleybear** [comment]
same issue

**Comment by SeaPuppy2006** [comment]
You know, typing 'same here' is counter-productive
Wait.

**Comment by Lorgborg** [comment]
what is the programming language of the script you are trying to run?

**Comment by kerrygip** [comment]
I was trying to run C++ and i got that issue

**Comment by Gradleybear** [comment]
I was trying to run Java

**Comment by hyeongeunji** [comment]
same issue :(

**Comment by Srikanth421** [comment]
Same issue. I don't know if this helps but the issue started for me after I changed the folder name. I was running a helloworld.c program and it worked fine yesterday and today after I changed the folder name it sent me here.

**Comment by lucasfuentes00** [comment]
same issue:.....:(

**Comment by Finay** [comment]
^

**Comment by tony-zhao666** [comment]
same issue when i running C#

**Comment by cbracketdash** [comment]
same issue when I try to run gcc on c file

**Comment by Neel166** [comment]
same issue
[LICENSE.txt](https://github.com/rgbkrk/atom-script/files/5714304/LICENSE.txt)
![logo](https://user-images.githubusercontent.com/72777156/102587886-957d5800-40da-11eb-97dc-d1f4c337079c.png)
![logo-cropped](https://user-images.githubusercontent.com/72777156/102587892-97471b80-40da-11eb-8006-5865089cd435.png)

**Comment by Neel166** [comment]
[atom.io](url)

**Comment by njberman** [comment]
SAME ISSUE :((
