### ISSUE TITLE
[Windows] Python + UTF-8 Encoding?

### ISSUE THREAD

**Issue by Braintelligence** [atom-community/atom-script#214]
Hi there,

when executing Python3 code with

```
print(" STRING ")
```

Where STRING contains letters like `öüä`, there's a problem with the encoding. It shows as `�`. (While the console in windows command prompt shows it correctly.)

If I use `#coding=latin-1` it works but this shouldn't be necessary!

Sorry if I missed this issue within the others.
Please help me out =(

**Comment by erran** [comment]
@Braintelligence can you confirm whether adding the special coding comment resolves this issue for you? I believe it resolved #252.

**Comment by Braintelligence** [comment]
I'm very sorry but I am not using Atom editor anymore since this issue is going on for over a year now: https://github.com/atom/atom-keymap/issues/35

For me this editor is not being maintained properly till proven otherwise.

**Comment by dbolton** [comment]
@erran Adding the utf-8 comment to the top of the file doesn't stop it from showing the question marks for me. Python 3.5.1, Atom 1.3.2, Windows 10.

**Comment by dbolton** [comment]
@erran and @Braintelligence I was able to find a workaround to the problem. 

For me, it looks like atom-script on Windows uses cp1252 (Windows 1252) encoding by default instead of utf-8 (the default encoding may depend on your locale and platform).

As a work-around you can specify the encoding as utf-8 in your code for the system out and error streams:

```
import sys
import io

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding = 'utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding = 'utf-8')

print ('öüä')
```

**Comment by Braintelligence** [comment]
@dbolton Thanks, but I really moved on and am now very happy with PyCharm. :)

**Comment by J-qak** [comment]
I haven't looked at **script** source codes, but shouldn't this have easy solution? Isn't it possible to just change encoding for console view on Windows?

**Comment by sinedanat** [comment]
After 2 years this problem still exists.
I use this plugin for runnning haskell code on Winwdos 7.
Maybe the simplest solution is to add another option for encoding in settings?

**Comment by rgbkrk** [comment]
If you've got a fix, please [submit a pull request](https://help.github.com/articles/about-pull-requests/).

**Comment by silvium** [comment]
@sinedanat after 3 years. And counting. VS Code is starting to look more and more inviting.

**Comment by rgbkrk** [comment]
I highly recommend using [Hydrogen](https://github.com/nteract/hydrogen) over this module for running your code. I don't have time to work on this one.

**Comment by darkpio** [comment]
solution found on internet : create a environment variable

PYTHONIOENCODING=utf-8
