### ISSUE TITLE
Add support for GitHub Markdown

### ISSUE THREAD

**Issue by wjandrea** [atom-community/atom-script#2220]
It would be nice if it just popped open the builtin "Markdown Preview" tab.

**Comment by wjandrea** [comment]
@aminya Duplicate of what, sorry? I don't see any open issues about adding support for Markdown.

**Comment by aminya** [comment]
@wjandrea Sorry. I ran a bot to detect duplicate issues, and it closed this. 

I don't understand what do you want to run inside a markdown.

**Comment by wjandrea** [comment]
@aminya No worries.

Atom has a builtin "Markdown Preview" feature, so it would be nice if Script popped that open instead of giving an error.

**Comment by aminya** [comment]
Not sure if that is executing markdown. Someone may say that it should run the currently selected code block.

**Comment by wjandrea** [comment]
`script` opens HTML in the web browser, so rendering Markdown is pretty much the same thing.

**Comment by aminya** [comment]
You can use markdown-preview-plus to view the markdown. We can add an adapter to call that package.

https://atom.io/packages/markdown-preview-plus

**Comment by wjandrea** [comment]
I figured out a hacky way to do it: override the keyboard shortcut lower in the keymap, specifically for Markdown files. For example, I'm using this:

```coffee
'.platform-linux atom-text-editor':
  'f5': 'script:run'

'.platform-linux atom-text-editor[data-grammar="source gfm"]':
  'f5': 'markdown-preview:toggle'  # Overrides above keymap F5:script-run
```

**Comment by wjandrea** [comment]
@aminya You don't even need to call Markdown Preview Plus since Markdown Preview is built-in. Though it'd be good to support both, I guess.

**Comment by wjandrea** [comment]
cleaning up now that Atom is sunsetted
