### ISSUE TITLE
Script Java ignores .classpath (at least when building)

### ISSUE THREAD

**Issue by ParadoxV5** [atom-community/atom-script#2282]
… where `.classpath` is used by the Eclipse JDT which [`ide-java`](https://atom.io/packages/ide-java) uses behind-the-scenes.

OS: `Windows 10`
Atom: `1.52.0-beta0`
Script: `3.26.0`

Reproduce: `.classpath`
```xml
<?xml version="1.0" encoding="UTF-8"?>
<classpath>
  <classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>
  <classpathentry kind="src" path=""/>
  <classpathentry kind="output" path=".bin"/>
</classpath>
```

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
