### ISSUE TITLE
failed to download script

### ISSUE THREAD

**Issue by Eli-Bates4454** [atom-community/atom-script#2430]
Installing “script@3.31.1” failed.Hide output…

npm ERR! Unexpected end of JSON input while parsing near '...3","@babel/helper-plu'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Eli Bates\.atom\.apm\_logs\2021-03-24T17_00_46_922Z-debug.log

**Comment by Eli-Bates4454** [comment]
I'm not sure why it wont download

**Comment by aminya** [comment]
Please re-download. That's an [apm issue](https://github.com/atom/apm/issues/919)

**Comment by erwindr** [comment]
I cannot update Script either. 

Updating to “script@3.31.1” failed.Hide output…
EACCES: permission denied, unlink '/Users/myusername/.atom/packages/script/.eslintignore'

I have no clue what to do, please help. I cannot uninstall the Script package, as it results in the same failure

Uninstalling “script” failed.Hide output…
Failed to delete script: EACCES: permission denied, unlink '/Users/myusername/.atom/packages/script/.eslintignore'

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall script
```
Clear your cache then

```
apm install script
```

https://github.com/atom/apm/issues/919
