### ISSUE TITLE
Unable to update Script

### ISSUE THREAD

**Issue by erwindr** [atom-community/atom-script#2445]
I cannot update Script on Mac.

Updating to “script@3.31.1” failed.Hide output…
EACCES: permission denied, unlink '/Users/myusername/.atom/packages/script/.eslintignore'

I have no clue what to do, please help. I cannot uninstall the Script package, as it results in the same failure

Uninstalling “script” failed.Hide output…
Failed to delete script: EACCES: permission denied, unlink '/Users/myusername/.atom/packages/script/.eslintignore'

**Comment by kokoro4869** [comment]
Same. When I try to uninstall this package, there is a message saying:
-------------------------------------------------------------------------
Failed to delete atom-script: EPERM: operation not permitted, unlink 'C:\Users\myuser\.atom\packages\atom-script\.git\objects\pack\pack-2e7204578477698ca92837efb3a3f62cd0a7f92a.idx'

**Comment by erwindr** [comment]
> Same. When I try to uninstall this package, there is a message saying:
> 
> Failed to delete atom-script: EPERM: operation not permitted, unlink 'C:\Users\myuser.atom\packages\atom-script.git\objects\pack\pack-2e7204578477698ca92837efb3a3f62cd0a7f92a.idx'

I completely uninstalled Atom from my Macbook, and thereafter reinstalled it, worked for me! https://discuss.atom.io/t/how-to-completely-uninstall-atom-for-mac/9084/41

**Comment by kokoro4869** [comment]
Thanks!!

**Comment by aminya** [comment]
Please re-download. This is an apm issue

```
apm uninstall script
```
Clear your cache then

```
apm install script
```

https://github.com/atom/apm/issues/919
