### ISSUE TITLE
Add support for CSS

### ISSUE THREAD

**Issue by Kamrang2004** [atom-community/atom-script#2447]
i am getting this error in my code editor atom:

Command not configured for CSS!

Add an issue on GitHub or send your own Pull Request.

^C

this happens to all my css files, here is a sample of one of my files:

----------------------------------------------------------------------------------------------------------

*{
  box-sizing: border-box;
  margin: 0;
  padding: 0;
}

.belowbar a{
  color: white;
  text-decoration: none;
  font-family: PT Sans Narrow, sans-serif;
}

ul.belowbar{
  display: flex;
  justify-content: flex-start;
  margin-right: auto;
  align-items: center;
  padding: 30px 10%;
  background: rgb(32, 32, 32);
}

.belowbar{
  list-style: none;
}

.belowbar li{
  display: inline-block;
  padding: 0px 25px;
}

.belowbar li a{
  transition: all 0.3s ease 0s;
  color: white;
}

ul.belowbar{
  background: rgb(32, 32, 32);
  height: 10px;
  border-bottom: orange;
}

.belowbar a:hover{
  color: orange;
}

----------------------------------------------------------------------------------------------------------

this error also shows even when I delete all the code and run it,
this error did not show a week ago please help if you know :)

**Comment by aminya** [comment]
We cannot execute CSS.
