### ISSUE TITLE
Add support for TypeScript

### ISSUE THREAD

**Issue by jamescrosswell** [atom-community/atom-script#398]
Would be great to see typescript support... [atom-typescript](https://atom.io/packages/atom-typescript) already provides really nice typescript editing but I haven't found an easy way to run these scripts (it's possible to switch to the compiled .js output and run that - but that's just a pain :-(

**Comment by erran** [comment]
@jamescrosswell Shouldn't be hard, we'd just need to add TypeScript to grammars.coffee.

1. How would you execute a TypeScript file?
2. How would you execute a selection of TypeScript code?

**Comment by DenisCarriere** [comment]
A good way that I'm executing Typescript at the moment is using [`ts-node`](https://github.com/TypeStrong/ts-node), it seems to work right out of the box.

```js
// File: test.ts
import * as _ from 'lodash'

const foo = (bar: string) => {
  return bar
}
console.log(foo('bar'))
```
```sh
$ ts-node test.ts
bar
```

**Comment by aminya** [comment]
TypeScript is already supported. Install ts-node:
```
npm install -g ts-node
```
