### ISSUE TITLE
How to run java code in windows 

### ISSUE THREAD

**Issue by angelssilva** [atom-community/atom-script#556]
![nash](https://cloud.githubusercontent.com/assets/14025254/9560371/30a0cabe-4dd5-11e5-83a5-7e238438560b.PNG)
whenever i try to run a java code i get this error, any idea how to fixit? thx

**Comment by inefoy** [comment]
up

**Comment by jigga** [comment]
I have the exact same problem and the first dozen of articles returned by googling "run java class from atom" do not provide an answer/solution.

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
