### ISSUE TITLE
Atom is Unable to Run Python

### ISSUE THREAD

**Issue by vmesel** [atom-community/atom-script#705]
Hello,

Im trying to run a Python code in Atom with Script and it keeps giving me this error: http://prntscr.com/9i66bs

How can I fix it?

**Comment by rgbkrk** [comment]
Try with the latest release we just shipped, there were issues with executing on Windows for Python and Java.

**Comment by vmesel** [comment]
I already tried to install the latest version! I've got a different error: YAPF: unable to open yapf

**Comment by vmesel** [comment]
Im having the same error with the latest version!

**Comment by EntilZha** [comment]
This still an issue?

**Comment by MrSassyBritches** [comment]
I am also having this issue, script runs in other IDEs/text editors, but not with this extension.
