### ISSUE TITLE
javac: file not found

### ISSUE THREAD

**Issue by JohnnyUrosevic** [atom-community/atom-script#808]
Happens with all java files, manually using cmd works

**Comment by viyatgandhi** [comment]
@JohnnyUrosevic I had a same problem if you are win user then set javac path in your PATH variable, It worked for me.

**Comment by biaocy** [comment]
@JohnnyUrosevic try specify current working directory in "Run Options"

**Comment by abhay676** [comment]
@JohnnyUrosevic  same problem happen

**Comment by keval-khawane** [comment]
1) set javac path in your PATH 
or
2)close file and reopen using atom ide

**Comment by aminya** [comment]
You need to add the java bin directory into your environment path. Something like https://stackoverflow.com/questions/9612941/how-to-set-java-environment-path-in-ubuntu. 

Google "Add java path {YOUR OS} "

_Originally posted by @hyobyun in https://github.com/atom-community/atom-script/issues/1809#issuecomment-463668785_
