### ISSUE TITLE
Caused by  Japanese chars when running Java.

### ISSUE THREAD

**Issue by takumin99** [atom-community/atom-script#900]
About a bug caused by  Japanese chars when running Java.

See these pictures.

Normal
![default](https://cloud.githubusercontent.com/assets/17415633/14759968/e4d53a7c-0970-11e6-9565-d74faeabb3df.PNG)

Error
![2](https://cloud.githubusercontent.com/assets/17415633/14759970/e76efe80-0970-11e6-987d-8cdff1b30262.PNG)

Installed package version is v3.7.0.
[Atom] v1.7.2
[OS]Windows 8.1 x64
[javac] 1.8.0_92
[java]1.8.0_92
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
