### ISSUE TITLE
Issue with script regarding boxes wrapping around each line.

### ISSUE THREAD

**Issue by rayto510** [atom-community/atom-script#920]
Boxes are wrapped around each line in the console. Need help getting rid of it.
<img width="1280" alt="screen shot 2016-05-11 at 11 06 59 am" src="https://cloud.githubusercontent.com/assets/16063953/15191210/87759e98-1768-11e6-8301-01c989a6e6f3.png">

**Comment by nixel2007** [comment]
Does it happen with standard UI theme?

**Comment by rayto510** [comment]
It doesn't. The boxes disappeared, but now I could see spaces between some
line for all themes.[image: Inline image 1]
