### ISSUE TITLE
help: run java failed

### ISSUE THREAD

**Issue by QiiSyhx** [atom-community/atom-script#974]
`import java.util.*;

public class Test{
   public static void main(String[] args){
      Calendar c = Calendar.getInstance();
      // Date d = c.getTime();
      // Date d2 = d;
      c.set(2000,1,1,1,1,1);
      Calendar c2 = Calendar.getInstance();
      System.out.println(c.getTime());
      System.out.println(c2.getTime());
   }
}
`

result:
javac: ��Ч�ı���: /c javac -Xlint Test.java && java Test
�÷�: javac <options> <source files>
-help �����г����ܵ�ѡ��
[Finished in 0.313s]

in cli:
D:\Go\project\src\hello>javac -Xlint Test.java && java Test
Tue Feb 01 01:01:01 CST 2000
Fri Jun 17 17:31:16 CST 2016

**Comment by peanuts** [comment]
javac: �t�@�C�����������܂���: test6.java
�g�p���@: javac <options> <source files>
�g�p�\�ȃI�v�V�����̃��X�g�ɂ��ẮA-help���g�p���܂�
[Finished in 0.202s]

---
**I had the same problem...**

**Comment by xiligey** [comment]
ME TOO, SOMEONE HELP US POOR GUY.

**Comment by nixel2007** [comment]
Is javac in your PATH?
can you run 'javac' from command line?

**Comment by xiligey** [comment]
I can ryn javac from command line, javac is in my PATH, but still can't run it.

**Comment by JaedongLee** [comment]
I have the same problem 

[Command: cmd '/c javac -Xlint HelloWorld.java && java HelloWorld']
javac: �Ҳ����ļ�: HelloWorld.java
�÷�: javac <options> <source files>
-help �����г����ܵ�ѡ��
[Finished in 0.356s]

I can run it form cmd,when I find the answer I will tall you guys

**Comment by aminya** [comment]
Should be fixed in #2470. Let me know if it is not.
